kinematic_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - foundation_fork
    - fork_forearm
    - forearm_hand
    - hand_fork
    - fork_end
  gains:
    foundation_fork:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fork_forearm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forearm_hand:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hand_fork:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fork_end:
      p: 100
      d: 1
      i: 1
      i_clamp: 1