controller_list:
  - name: fake_kinematic_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1_shoulder
      - joint2_forearm
      - joint3_hand
      - joint4_handyaw
      - joint5_end
initial:  # Define initial robot poses per group
  - group: kinematic
    pose: home