controller_list:
  - name: kinematic_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1_shoulder
      - joint2_forearm
      - joint3_hand
      - joint4_handyaw
      - joint5_end