kinematic_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint4
    - joint3
    - joint2
    - joint1
  gains:
    joint4:
      p: 1500
      d: 150
      i: 115
      i_clamp: 1
    joint3:
      p: 1800
      d: 15
      i: 100
      i_clamp: 1
    joint2:
      p: 700
      d: 10
      i: 1
      i_clamp: 1
    joint1:
      p: 70
      d: 1
      i: 1
      i_clamp: 1