controller_list:
  - name: fake_kinematic_controller
    type: $(arg fake_execution_type)
    joints:
      - foundation_fork
      - fork_forearm
      - forearm_hand
      - hand_fork
      - fork_end
initial:  # Define initial robot poses per group
  - group: kinematic
    pose: home