controller_list:
  - name: kinematic_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - foundation_fork
      - fork_forearm
      - forearm_hand
      - hand_fork
      - fork_end