# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    basic_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

basic_controller:
  ros__parameters:
    joints:
      - foundation_fork
      - fork_forearm
      - forearm_hand
      - hand_fork
      - fork_end
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity