kinematic_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1_shoulder
    - joint2_forearm
    - joint3_hand
    - joint4_handyaw
    - joint5_end
  gains:
    joint1_shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2_forearm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3_hand:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4_handyaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5_end:
      p: 100
      d: 1
      i: 1
      i_clamp: 1